# Generated by Django 3.2.4 on 2022-05-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('alt', models.TextField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('alt', models.TextField(blank=True, default='', max_length=200)),
                ('created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='', max_length=400)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'types',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('link', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('latitude', models.TextField(blank=True, default='')),
                ('longitude', models.TextField(blank=True, default='')),
                ('city', models.TextField(max_length=50)),
                ('area', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='articles.Photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.type')),
                ('videos', models.ManyToManyField(blank=True, to='articles.Video')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=50)),
                ('latitude', models.TextField(max_length=200)),
                ('longitude', models.TextField(max_length=200)),
                ('area', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='articles.Photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.type')),
                ('videos', models.ManyToManyField(blank=True, to='articles.Video')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('address', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=50)),
                ('latitude', models.TextField(max_length=200)),
                ('longitude', models.TextField(max_length=200)),
                ('area', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(blank=True, to='articles.Photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.type')),
                ('videos', models.ManyToManyField(blank=True, to='articles.Video')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
